name: release-to-maven-central
on:
  workflow_dispatch:
    inputs:
      releaseversion:
        description: 'Release version'
        required: true
        default: '2.4.0'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Will start a Maven Central upload with version ${{ github.event.inputs.releaseversion }}"
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 8
          server-id: oss.sonatype.org
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          token: ${{ secrets.PACKAGE_PUBLISH_TOKEN }}

#      - name: Set projects Maven version to GitHub Action GUI set version
#        run: mvn versions:set "-DnewVersion=${{ github.event.inputs.releaseversion }}"

#      - name: Publish package
#        run: mvn --batch-mode clean deploy -P central-deploy -DskipTests=true
#        env:
#          MAVEN_USERNAME: ${{ secrets.OSS_SONATYPE_USERNAME }}
#          MAVEN_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}

      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Publish JAR
        run: mvn -B release:prepare release:perform
        env:
          MAVEN_USERNAME: ${{ secrets.OSS_SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.PACKAGE_PUBLISH_TOKEN }}